// DevPad — Copyright © 2026 bachbnt. Proprietary.
//
//  Localization.swift
//  DevPad
//
//  In-memory string catalog for English and Vietnamese.
//  Keeping the strings in code (rather than .strings / .xcstrings files)
//  lets us switch language at runtime without restarting the app.
//

import Foundation

enum Localization {

    /// Returns the localized string for `key` in the given language.
    /// Falls back to English, then to the raw key when no entry is found.
    static func string(for key: String, language: AppLanguage) -> String {
        let code = language.resolvedCode
        if let table = catalog[code], let value = table[key] {
            return value
        }
        if let value = catalog["en"]?[key] {
            return value
        }
        return key
    }

    // MARK: - Catalog

    private static let catalog: [String: [String: String]] = [
        "en": en,
        "vi": vi
    ]

    // MARK: English

    private static let en: [String: String] = [
        // App / sidebar
        "app.name":                          "DevPad",
        "sidebar.json":                      "JSON Formatter",
        "sidebar.xml":                       "XML Formatter",
        "sidebar.sql":                       "SQL Formatter",
        "sidebar.url":                       "URL Parser",
        "sidebar.qr":                        "QR Generator",
        "sidebar.jwt":                       "JWT Inspector",
        "sidebar.regex":                     "Regex Tester",
        "sidebar.hash":                      "Hash Generator",
        "sidebar.diff":                      "Diff Compare",
        "sidebar.clipboard":                 "Clipboard History",
        "sidebar.dropshelf":                 "Drop Shelf",
        "sidebar.settings":                  "Settings",
        "sidebar.search.placeholder":        "Search tools…",
        "sidebar.search.clear":              "Clear search",
        "sidebar.search.empty":              "No tools match \"%@\"",

        // Common buttons / labels
        "common.paste":                      "Paste",
        "common.copy":                       "Copy",
        "common.clear":                      "Clear",
        "common.clearAll":                   "Clear All",
        "common.cancel":                     "Cancel",
        "common.indent":                     "Indent:",
        "common.indent.2":                   "2 spaces",
        "common.indent.4":                   "4 spaces",
        "common.indent.tab":                 "Tab",
        "common.format":                     "Format",
        "common.minify":                     "Minify",
        "common.compare":                    "Compare",

        // JSON
        "json.placeholder":                  "Paste your JSON here…",
        "json.error.prefix":                 "Invalid JSON",
        "json.error.empty":                  "Input is empty.",
        "json.error.encoding":               "Cannot encode input as UTF-8.",

        // XML
        "xml.placeholder":                   "Paste your XML here…",
        "xml.error.prefix":                  "Invalid XML",
        "xml.error.empty":                   "Input is empty.",
        "xml.error.unclosed":                "Unclosed tag.",
        "xml.error.notokens":                "No tokens parsed.",

        "sql.placeholder":                   "Paste your SQL here…",
        "sql.error.prefix":                  "Invalid SQL",
        "sql.error.empty":                   "Input is empty.",

        // URL Parser
        "url.placeholder":                   "Paste a URL here…",
        "url.parse":                         "Parse",
        "url.scheme":                        "Scheme",
        "url.user":                          "User",
        "url.password":                      "Password",
        "url.host":                          "Host",
        "url.port":                          "Port",
        "url.path":                          "Path",
        "url.query":                         "Query string",
        "url.queryParams":                   "Query parameters",
        "url.fragment":                      "Fragment",
        "url.error.invalid":                 "Couldn't parse URL.",
        "url.error.empty":                   "Input is empty.",
        "url.error.prefix":                  "Invalid URL",
        "url.empty.title":                   "Paste a URL to parse it",
        "url.empty.hint":                    "Splits the URL into scheme, host, path, query parameters, and fragment.",
        "url.queryParams.empty":             "(no query parameters)",
        "url.absent":                        "—",

        // QR Generator
        "qr.mode.generate":                  "Generate",
        "qr.mode.scan":                      "Scan",
        "qr.placeholder":                    "Type or paste text / URL to encode as QR…",
        "qr.generate":                       "Generate QR",
        "qr.save":                           "Save as PNG…",
        "qr.copy":                           "Copy QR image",
        "qr.errorCorrection":                "Error correction",
        "qr.errorCorrection.L":              "Low (~7% recovery)",
        "qr.errorCorrection.M":              "Medium (~15% recovery)",
        "qr.errorCorrection.Q":              "Quartile (~25% recovery)",
        "qr.errorCorrection.H":              "High (~30% recovery)",
        "qr.scan.dropHint":                  "Drop a QR-code image here, or click Choose file…",
        "qr.scan.choose":                    "Choose file…",
        "qr.scan.paste":                     "Paste from clipboard",
        "qr.scan.result":                    "Decoded text",
        "qr.scan.empty":                     "No image yet",
        "qr.scan.copy":                      "Copy decoded text",
        "qr.scan.openLink":                  "Open as link",
        "qr.error.empty":                    "Enter text to encode.",
        "qr.error.tooLong":                  "Text is too long for a QR code.",
        "qr.error.invalidImage":             "Couldn't read the image.",
        "qr.error.noQR":                     "No QR code found in this image.",
        "qr.error.prefix":                   "QR error",
        "qr.saved":                          "Saved to %@",
        "qr.centerIcon":                     "Center icon",
        "qr.centerIcon.add":                 "Add icon",
        "qr.centerIcon.remove":              "Remove icon",
        "qr.centerIcon.hint":                "Adding a center icon hides part of the QR — Quartile or High error correction is recommended.",
        "qr.scan.source.image":              "Image",
        "qr.scan.source.camera":             "Camera",
        "qr.scan.camera.permission":         "DevPad needs camera access to scan QR codes with your webcam.",
        "qr.scan.camera.allow":              "Allow camera",
        "qr.scan.camera.denied":             "Camera access denied",
        "qr.scan.camera.deniedHint":         "Open System Settings → Privacy & Security → Camera and enable DevPad to use this feature.",
        "qr.scan.camera.openSettings":       "Open System Settings…",
        "qr.scan.camera.start":              "Start camera",
        "qr.scan.camera.stop":               "Stop camera",
        "qr.scan.camera.stopped":            "Camera is stopped",
        "qr.scan.camera.hint.running":       "Point a QR code at the camera — it scans continuously.",
        "qr.scan.camera.hint.idle":          "Press Start to begin scanning.",

        // JWT
        "jwt.mode.decode":                   "Decode",
        "jwt.mode.sign":                     "Sign",
        "jwt.placeholder":                   "Paste a JWT here (xxx.yyy.zzz)…",
        "jwt.decode":                        "Decode",
        "jwt.header":                        "Header",
        "jwt.payload":                       "Payload",
        "jwt.signature":                     "Signature",
        "jwt.claims":                        "Claims",
        "jwt.claim.iss":                     "Issuer (iss)",
        "jwt.claim.sub":                     "Subject (sub)",
        "jwt.claim.aud":                     "Audience (aud)",
        "jwt.claim.exp":                     "Expires (exp)",
        "jwt.claim.iat":                     "Issued at (iat)",
        "jwt.claim.nbf":                     "Not before (nbf)",
        "jwt.claim.jti":                     "JWT ID (jti)",
        "jwt.status.valid":                  "Valid",
        "jwt.status.expired":                "Expired %@",
        "jwt.status.notYet":                 "Not active until %@",
        "jwt.status.noExp":                  "No expiration",
        "jwt.verify.title":                  "Verify signature",
        "jwt.verify.secret":                 "Secret",
        "jwt.verify.publicKey":              "Public key (PEM)",
        "jwt.verify.secret.placeholder":     "HMAC secret",
        "jwt.verify.publicKey.placeholder":  "-----BEGIN PUBLIC KEY-----\\n…\\n-----END PUBLIC KEY-----",
        "jwt.verify.run":                    "Verify",
        "jwt.verify.success":                "Signature is valid",
        "jwt.verify.failure":                "Signature does NOT verify",
        "jwt.verify.hint.hmac":              "For HS256/384/512 the signing secret is a plain string.",
        "jwt.verify.hint.asym":              "For RS*/ES* paste the PEM-encoded public key.",
        "jwt.sign.header":                   "Header JSON",
        "jwt.sign.payload":                  "Payload JSON",
        "jwt.sign.algorithm":                "Algorithm",
        "jwt.sign.secret":                   "Secret",
        "jwt.sign.run":                      "Generate token",
        "jwt.sign.output":                   "Token",
        "jwt.sign.hint":                     "DevPad signs HMAC tokens only (HS256/384/512). Use a CLI for RSA/ECDSA private keys.",
        "jwt.error.prefix":                  "JWT error",
        "jwt.algorithm":                     "Algorithm",
        "jwt.type":                          "Type",
        "jwt.kid":                           "Key ID (kid)",
        "jwt.empty.title":                   "Paste a JWT to inspect it",
        "jwt.empty.hint":                    "Splits the token into header, payload, signature, and parses standard claims with status.",

        // Regex Tester
        "regex.mode.match":                  "Match",
        "regex.mode.replace":                "Replace",
        "regex.pattern.placeholder":         "Regex pattern…",
        "regex.testText.placeholder":        "Paste text to test the pattern against…",
        "regex.flag.caseInsensitive":        "case-insensitive",
        "regex.flag.multiline":              "multiline",
        "regex.flag.dotAll":                 "dot matches newline",
        "regex.flag.unicode":                "unicode boundaries",
        "regex.matchCount":                  "%d match(es)",
        "regex.match.empty":                 "No matches",
        "regex.group.empty":                 "(no match)",
        "regex.replace.template":            "Replacement",
        "regex.replace.template.placeholder": "Use $1, $2, $& for back-references…",
        "regex.replace.summary":             "Replaced %d match(es)",
        "regex.replace.copyResult":          "Copy result",
        "regex.replace.empty":               "Replacement output will appear here.",
        "regex.error.prefix":                "Invalid regex",
        "regex.empty.title":                 "Type a regex pattern to start",
        "regex.empty.hint":                  "Pattern matches highlight inline in the test text; capture groups are listed below.",
        "regex.cheatsheet":                  "Cheat sheet",
        "regex.cheatsheet.title":            "Common tokens",
        "regex.cheatsheet.replace":          "Replacement tokens",
        "regex.cheat.anchors":               "Start / end of line",
        "regex.cheat.wordBoundary":          "Word boundary",
        "regex.cheat.classes":               "Digit / word / whitespace",
        "regex.cheat.charSet":               "Any of / none of",
        "regex.cheat.quantifiers":           "Zero+ / one+ / optional",
        "regex.cheat.range":                 "Between 2 and 5",
        "regex.cheat.group":                 "Capturing group",
        "regex.cheat.nonCapture":            "Non-capturing group",
        "regex.cheat.named":                 "Named capture",
        "regex.cheat.lookahead":             "Positive / negative lookahead",
        "regex.cheat.alt":                   "Either / or",
        "regex.cheat.backref":               "N-th capture",
        "regex.cheat.fullMatch":             "Full match",
        "regex.cheat.literalDollar":         "Literal $",
        "regex.run.match":                   "Match",
        "regex.run.apply":                   "Apply",

        // Hash Generator
        "hash.mode.text":                    "Text",
        "hash.mode.file":                    "File",
        "hash.mode.hmac":                    "HMAC",
        "hash.input.placeholder":            "Paste text to hash…",
        "hash.format":                       "Format",
        "hash.format.hex":                   "Hex",
        "hash.format.base64":                "Base64",
        "hash.copyAll":                      "Copy all",
        "hash.compare":                      "Compare with",
        "hash.compare.placeholder":          "Paste an expected hash to verify…",
        "hash.compare.match":                "Match",
        "hash.hashing":                      "Hashing…",
        "hash.file.dropHint":                "Drop a file here to hash it",
        "hash.file.dropSub":                 "Or use Choose file… below. Each algorithm is streamed off the main thread.",
        "hash.file.choose":                  "Choose file…",
        "hash.hmac.message":                 "Message",
        "hash.hmac.key":                     "Secret key",
        "hash.hmac.message.placeholder":     "Paste the message to authenticate…",
        "hash.hmac.key.placeholder":         "HMAC secret",
        "hash.hmac.algorithm":               "Algorithm",
        "hash.hmac.output":                  "HMAC",
        "hash.hmac.empty":                   "Type a message and key to generate an HMAC.",
        "hash.error.prefix":                 "Hash error",
        "hash.run.text":                     "Hash",
        "hash.run.hmac":                     "Generate",

        // Diff
        "diff.original":                     "Original",
        "diff.changed":                      "Changed",
        "diff.placeholder.left":             "Paste original text…",
        "diff.placeholder.right":            "Paste changed text…",
        "diff.placeholder.empty":            "Enter text on both sides and tap Compare",
        "diff.summary.added":                "%d added",
        "diff.summary.removed":              "%d removed",
        "diff.summary.modified":             "%d modified",
        "diff.identical":                    "Both sides are identical.",
        "diff.viewMode":                     "View",
        "diff.viewMode.split":               "Split",
        "diff.viewMode.unified":             "Unified",
        "diff.context":                      "Context",
        "diff.hunk.gap":                     "… %d unchanged line(s) hidden …",
        "diff.options.whitespace":           "Ignore whitespace",
        "diff.options.case":                 "Ignore case",

        // Clipboard
        "clipboard.itemCount":               "%d items",
        "clipboard.itemCount.one":           "1 item",
        "clipboard.empty.title":             "Clipboard history is empty",
        "clipboard.empty.hint":              "Copy anything (Cmd+C) — it will appear here.",
        "clipboard.selectItem":              "Select an item on the left to view details",
        "clipboard.copyAgain":               "Copy again",
        "clipboard.pin":                     "Pin",
        "clipboard.unpin":                   "Unpin",
        "clipboard.delete":                  "Delete",
        "clipboard.deleteThis":              "Delete this item",
        "clipboard.confirm.title":           "Clear all clipboard history?",
        "clipboard.confirm.unpinned":        "Delete unpinned only",
        "clipboard.confirm.all":             "Delete all (including pinned)",
        "clipboard.kind.text":               "Text",
        "clipboard.kind.image":              "Image",
        "clipboard.image.unavailable":       "(Image not available)",
        "clipboard.preview.empty":           "(empty)",
        "clipboard.preview.image":           "🖼 Image — %d×%d, %d KB",
        "clipboard.section.pinned":          "Pinned",
        "clipboard.section.other":           "History",
        "clipboard.purePaste":               "Pure Paste",
        "clipboard.purePaste.tooltip":       "Auto-strip rich text formatting from copied text. Paste always lands as plain text.",

        // Menu bar
        "menubar.open":                      "Open DevPad",
        "menubar.empty":                     "No items yet",
        "menubar.quit":                      "Quit DevPad",

        // Drop Shelf — popup
        "dropshelf.title":                   "Drop Shelf",
        "dropshelf.empty":                   "Drop files here",
        "dropshelf.hint":                    "Drag files in, then drag them out together to a new destination.",
        "dropshelf.count":                   "%d file(s)",
        "dropshelf.clear":                   "Clear",
        "dropshelf.close":                   "Close",
        // Drop Shelf — main view / menubar section
        "dropshelf.toggle":                  "Enable",
        "dropshelf.toggleHint":              "When on, a floating shelf appears whenever you start dragging files anywhere on the Mac.",
        "dropshelf.disabled.title":          "Drop Shelf is off",
        "dropshelf.disabled.hint":           "Turn it on to start collecting files while you drag.",
        "dropshelf.list.empty":              "No files yet",
        "dropshelf.list.empty.hint":         "Drag files into the floating shelf and they'll appear here.",
        "dropshelf.remove":                  "Remove from shelf",
        // Menu-bar tab labels
        "menubar.tab.clipboard":             "Clipboard",
        "menubar.tab.dropshelf":             "Drop Shelf",

        // Settings
        "settings.title":                    "Settings",
        "settings.section.appearance":       "Appearance",
        "settings.theme":                    "Theme",
        "settings.theme.system":             "System",
        "settings.theme.light":              "Light",
        "settings.theme.dark":               "Dark",
        "settings.theme.footer":             "Choose how DevPad looks. \"System\" follows your macOS appearance.",
        "settings.section.language":         "Language",
        "settings.language":                 "Language",
        "settings.language.system":          "System",
        "settings.language.english":         "English",
        "settings.language.vietnamese":      "Tiếng Việt",
        "settings.language.footer":          "The change applies immediately, no restart required.",

        // Settings — Drop Shelf
        "settings.section.dropshelf":        "Drop Shelf",
        "settings.dropshelf":         "Enable",
        "settings.dropshelf.footer":         "Show a floating shelf when you start dragging files. Drop files into it, then drag the bundle out to a new destination.",

        // Settings — About / License
        "settings.section.about":            "About",
        "settings.about.version":            "Version",
        "settings.about.copyright":          "Copyright",
        "settings.about.copyright.value":    "© 2026 bachbnt. All rights reserved.",
        "settings.about.license":            "License",
        "settings.about.license.value":      "Proprietary",
        "settings.about.license.footer":     "Unauthorized copying, modification or distribution of this software is strictly prohibited without prior written permission.",

        // Window
        "window.minSize":                    "DevPad"
    ]

    // MARK: Vietnamese

    private static let vi: [String: String] = [
        "app.name":                          "DevPad",
        "sidebar.json":                      "Định dạng JSON",
        "sidebar.xml":                       "Định dạng XML",
        "sidebar.sql":                       "Định dạng SQL",
        "sidebar.url":                       "Phân tích URL",
        "sidebar.qr":                        "Tạo mã QR",
        "sidebar.jwt":                       "JWT Inspector",
        "sidebar.regex":                     "Regex Tester",
        "sidebar.hash":                      "Tạo Hash",
        "sidebar.diff":                      "So sánh khác biệt",
        "sidebar.clipboard":                 "Lịch sử Clipboard",
        "sidebar.dropshelf":                 "Khay thả file",
        "sidebar.settings":                  "Cài đặt",
        "sidebar.search.placeholder":        "Tìm công cụ…",
        "sidebar.search.clear":              "Xóa tìm kiếm",
        "sidebar.search.empty":              "Không có công cụ nào khớp \"%@\"",

        "common.paste":                      "Dán",
        "common.copy":                       "Sao chép",
        "common.clear":                      "Xóa",
        "common.clearAll":                   "Xóa tất cả",
        "common.cancel":                     "Hủy",
        "common.indent":                     "Thụt lề:",
        "common.indent.2":                   "2 dấu cách",
        "common.indent.4":                   "4 dấu cách",
        "common.indent.tab":                 "Tab",
        "common.format":                     "Định dạng",
        "common.minify":                     "Rút gọn",
        "common.compare":                    "So sánh",

        "json.placeholder":                  "Dán JSON vào đây…",
        "json.error.prefix":                 "JSON không hợp lệ",
        "json.error.empty":                  "Nội dung trống.",
        "json.error.encoding":               "Không thể mã hóa UTF-8.",

        "xml.placeholder":                   "Dán XML vào đây…",
        "xml.error.prefix":                  "XML không hợp lệ",
        "xml.error.empty":                   "Nội dung trống.",
        "xml.error.unclosed":                "Tag chưa đóng.",
        "xml.error.notokens":                "Không phân tích được token nào.",

        "sql.placeholder":                   "Dán SQL vào đây…",
        "sql.error.prefix":                  "SQL không hợp lệ",
        "sql.error.empty":                   "Nội dung trống.",

        "url.placeholder":                   "Dán URL vào đây…",
        "url.parse":                         "Phân tích",
        "url.scheme":                        "Giao thức",
        "url.user":                          "User",
        "url.password":                      "Mật khẩu",
        "url.host":                          "Máy chủ",
        "url.port":                          "Cổng",
        "url.path":                          "Đường dẫn",
        "url.query":                         "Query string",
        "url.queryParams":                   "Tham số query",
        "url.fragment":                      "Fragment",
        "url.error.invalid":                 "Không phân tích được URL.",
        "url.error.empty":                   "Nội dung trống.",
        "url.error.prefix":                  "URL không hợp lệ",
        "url.empty.title":                   "Dán URL để phân tích",
        "url.empty.hint":                    "Tách URL thành scheme, host, path, tham số query và fragment.",
        "url.queryParams.empty":             "(không có tham số)",
        "url.absent":                        "—",

        "qr.mode.generate":                  "Tạo",
        "qr.mode.scan":                      "Quét",
        "qr.placeholder":                    "Gõ hoặc dán text / URL để tạo QR…",
        "qr.generate":                       "Tạo QR",
        "qr.save":                           "Lưu PNG…",
        "qr.copy":                           "Copy ảnh QR",
        "qr.errorCorrection":                "Mức sửa lỗi",
        "qr.errorCorrection.L":              "Thấp (~7% phục hồi)",
        "qr.errorCorrection.M":              "Trung bình (~15% phục hồi)",
        "qr.errorCorrection.Q":              "Khá cao (~25% phục hồi)",
        "qr.errorCorrection.H":              "Cao (~30% phục hồi)",
        "qr.scan.dropHint":                  "Thả ảnh QR vào đây, hoặc bấm Chọn file…",
        "qr.scan.choose":                    "Chọn file…",
        "qr.scan.paste":                     "Dán từ clipboard",
        "qr.scan.result":                    "Nội dung giải mã",
        "qr.scan.empty":                     "Chưa có ảnh",
        "qr.scan.copy":                      "Copy text",
        "qr.scan.openLink":                  "Mở như liên kết",
        "qr.error.empty":                    "Nhập text để encode.",
        "qr.error.tooLong":                  "Text quá dài cho mã QR.",
        "qr.error.invalidImage":             "Không đọc được ảnh.",
        "qr.error.noQR":                     "Không tìm thấy mã QR trong ảnh.",
        "qr.error.prefix":                   "Lỗi QR",
        "qr.saved":                          "Đã lưu vào %@",
        "qr.centerIcon":                     "Icon giữa",
        "qr.centerIcon.add":                 "Thêm icon",
        "qr.centerIcon.remove":              "Xóa icon",
        "qr.centerIcon.hint":                "Icon giữa che bớt mã QR — nên dùng mức sửa lỗi Quartile hoặc High.",
        "qr.scan.source.image":              "Ảnh",
        "qr.scan.source.camera":             "Camera",
        "qr.scan.camera.permission":         "DevPad cần quyền truy cập camera để quét mã QR bằng webcam.",
        "qr.scan.camera.allow":              "Cho phép camera",
        "qr.scan.camera.denied":             "Đã từ chối quyền camera",
        "qr.scan.camera.deniedHint":         "Mở Cài đặt hệ thống → Quyền riêng tư & Bảo mật → Camera và bật DevPad để dùng tính năng này.",
        "qr.scan.camera.openSettings":       "Mở Cài đặt hệ thống…",
        "qr.scan.camera.start":              "Bắt đầu",
        "qr.scan.camera.stop":               "Dừng",
        "qr.scan.camera.stopped":            "Camera đang tắt",
        "qr.scan.camera.hint.running":       "Đưa mã QR vào camera — DevPad quét liên tục.",
        "qr.scan.camera.hint.idle":          "Bấm Bắt đầu để quét.",

        "jwt.mode.decode":                   "Decode",
        "jwt.mode.sign":                     "Sign",
        "jwt.placeholder":                   "Dán JWT vào đây (xxx.yyy.zzz)…",
        "jwt.decode":                        "Decode",
        "jwt.header":                        "Header",
        "jwt.payload":                       "Payload",
        "jwt.signature":                     "Signature",
        "jwt.claims":                        "Claims",
        "jwt.claim.iss":                     "Issuer (iss)",
        "jwt.claim.sub":                     "Subject (sub)",
        "jwt.claim.aud":                     "Audience (aud)",
        "jwt.claim.exp":                     "Hết hạn (exp)",
        "jwt.claim.iat":                     "Phát hành (iat)",
        "jwt.claim.nbf":                     "Không trước (nbf)",
        "jwt.claim.jti":                     "JWT ID (jti)",
        "jwt.status.valid":                  "Hợp lệ",
        "jwt.status.expired":                "Đã hết hạn %@",
        "jwt.status.notYet":                 "Chưa kích hoạt tới %@",
        "jwt.status.noExp":                  "Không hết hạn",
        "jwt.verify.title":                  "Xác minh chữ ký",
        "jwt.verify.secret":                 "Khóa bí mật",
        "jwt.verify.publicKey":              "Public key (PEM)",
        "jwt.verify.secret.placeholder":     "HMAC secret",
        "jwt.verify.publicKey.placeholder":  "-----BEGIN PUBLIC KEY-----\\n…\\n-----END PUBLIC KEY-----",
        "jwt.verify.run":                    "Xác minh",
        "jwt.verify.success":                "Chữ ký hợp lệ",
        "jwt.verify.failure":                "Chữ ký KHÔNG khớp",
        "jwt.verify.hint.hmac":              "HS256/384/512 dùng secret string thường.",
        "jwt.verify.hint.asym":              "RS*/ES* dán public key dạng PEM.",
        "jwt.sign.header":                   "Header JSON",
        "jwt.sign.payload":                  "Payload JSON",
        "jwt.sign.algorithm":                "Thuật toán",
        "jwt.sign.secret":                   "Secret",
        "jwt.sign.run":                      "Tạo token",
        "jwt.sign.output":                   "Token",
        "jwt.sign.hint":                     "DevPad chỉ ký HMAC (HS256/384/512). Dùng CLI riêng cho RSA/ECDSA private key.",
        "jwt.error.prefix":                  "JWT lỗi",
        "jwt.algorithm":                     "Thuật toán",
        "jwt.type":                          "Loại",
        "jwt.kid":                           "Key ID (kid)",
        "jwt.empty.title":                   "Dán JWT để phân tích",
        "jwt.empty.hint":                    "Tách token thành header, payload, signature và parse các claim tiêu chuẩn kèm trạng thái.",

        "regex.mode.match":                  "Tìm",
        "regex.mode.replace":                "Thay thế",
        "regex.pattern.placeholder":         "Mẫu regex…",
        "regex.testText.placeholder":        "Dán văn bản để kiểm tra mẫu…",
        "regex.flag.caseInsensitive":        "không phân biệt hoa thường",
        "regex.flag.multiline":              "đa dòng",
        "regex.flag.dotAll":                 "dấu chấm khớp newline",
        "regex.flag.unicode":                "ranh giới unicode",
        "regex.matchCount":                  "%d kết quả",
        "regex.match.empty":                 "Không có kết quả",
        "regex.group.empty":                 "(không khớp)",
        "regex.replace.template":            "Mẫu thay thế",
        "regex.replace.template.placeholder": "Dùng $1, $2, $& để tham chiếu…",
        "regex.replace.summary":             "Đã thay %d kết quả",
        "regex.replace.copyResult":          "Copy kết quả",
        "regex.replace.empty":               "Kết quả thay thế sẽ hiện ở đây.",
        "regex.error.prefix":                "Regex không hợp lệ",
        "regex.empty.title":                 "Nhập mẫu regex để bắt đầu",
        "regex.empty.hint":                  "Các đoạn khớp được tô vàng ngay trong văn bản; capture group liệt kê bên dưới.",
        "regex.cheatsheet":                  "Cheat sheet",
        "regex.cheatsheet.title":            "Ký hiệu thường dùng",
        "regex.cheatsheet.replace":          "Ký hiệu thay thế",
        "regex.cheat.anchors":               "Đầu / cuối dòng",
        "regex.cheat.wordBoundary":          "Ranh giới từ",
        "regex.cheat.classes":               "Chữ số / chữ / khoảng trắng",
        "regex.cheat.charSet":               "Bất kỳ trong / loại trừ",
        "regex.cheat.quantifiers":           "0+ / 1+ / tùy chọn",
        "regex.cheat.range":                 "Từ 2 đến 5 lần",
        "regex.cheat.group":                 "Nhóm capture",
        "regex.cheat.nonCapture":            "Nhóm không capture",
        "regex.cheat.named":                 "Nhóm đặt tên",
        "regex.cheat.lookahead":             "Lookahead dương / âm",
        "regex.cheat.alt":                   "Hoặc",
        "regex.cheat.backref":               "Tham chiếu nhóm N",
        "regex.cheat.fullMatch":             "Toàn bộ match",
        "regex.cheat.literalDollar":         "Ký tự $ thường",
        "regex.run.match":                   "Tìm",
        "regex.run.apply":                   "Thay thế",

        "hash.mode.text":                    "Văn bản",
        "hash.mode.file":                    "Tệp",
        "hash.mode.hmac":                    "HMAC",
        "hash.input.placeholder":            "Dán văn bản cần hash…",
        "hash.format":                       "Định dạng",
        "hash.format.hex":                   "Hex",
        "hash.format.base64":                "Base64",
        "hash.copyAll":                      "Copy tất cả",
        "hash.compare":                      "So với",
        "hash.compare.placeholder":          "Dán hash mong đợi để xác minh…",
        "hash.compare.match":                "Khớp",
        "hash.hashing":                      "Đang băm…",
        "hash.file.dropHint":                "Thả tệp vào đây để băm",
        "hash.file.dropSub":                 "Hoặc bấm Chọn tệp… bên dưới. Mỗi thuật toán đọc tệp ngoài main thread.",
        "hash.file.choose":                  "Chọn tệp…",
        "hash.hmac.message":                 "Thông điệp",
        "hash.hmac.key":                     "Khóa bí mật",
        "hash.hmac.message.placeholder":     "Dán thông điệp cần xác thực…",
        "hash.hmac.key.placeholder":         "HMAC secret",
        "hash.hmac.algorithm":               "Thuật toán",
        "hash.hmac.output":                  "HMAC",
        "hash.hmac.empty":                   "Nhập thông điệp và khóa để tạo HMAC.",
        "hash.error.prefix":                 "Lỗi hash",
        "hash.run.text":                     "Tạo hash",
        "hash.run.hmac":                     "Tạo HMAC",

        "diff.original":                     "Bản gốc",
        "diff.changed":                      "Bản sửa",
        "diff.placeholder.left":             "Dán văn bản gốc…",
        "diff.placeholder.right":            "Dán văn bản đã sửa…",
        "diff.placeholder.empty":            "Nhập văn bản hai bên và bấm So sánh",
        "diff.summary.added":                "Thêm %d",
        "diff.summary.removed":              "Xóa %d",
        "diff.summary.modified":             "Sửa %d",
        "diff.identical":                    "Hai bên giống hệt nhau.",
        "diff.viewMode":                     "Hiển thị",
        "diff.viewMode.split":               "Tách 2 cột",
        "diff.viewMode.unified":             "Ghép 1 cột",
        "diff.context":                      "Ngữ cảnh",
        "diff.hunk.gap":                     "… %d dòng không đổi đã ẩn …",
        "diff.options.whitespace":           "Bỏ qua khoảng trắng",
        "diff.options.case":                 "Bỏ qua hoa thường",

        "clipboard.itemCount":               "%d mục",
        "clipboard.itemCount.one":           "1 mục",
        "clipboard.empty.title":             "Chưa có gì trong lịch sử",
        "clipboard.empty.hint":              "Copy bất kỳ (Cmd+C) — sẽ xuất hiện ở đây.",
        "clipboard.selectItem":              "Chọn 1 mục bên trái để xem chi tiết",
        "clipboard.copyAgain":               "Copy lại",
        "clipboard.pin":                     "Ghim",
        "clipboard.unpin":                   "Bỏ ghim",
        "clipboard.delete":                  "Xóa",
        "clipboard.deleteThis":              "Xóa mục này",
        "clipboard.confirm.title":           "Xóa toàn bộ lịch sử clipboard?",
        "clipboard.confirm.unpinned":        "Chỉ xóa mục chưa ghim",
        "clipboard.confirm.all":             "Xóa tất cả (kể cả mục đã ghim)",
        "clipboard.kind.text":               "Văn bản",
        "clipboard.kind.image":              "Hình ảnh",
        "clipboard.image.unavailable":       "(Hình ảnh không khả dụng)",
        "clipboard.preview.empty":           "(trống)",
        "clipboard.preview.image":           "🖼 Hình — %d×%d, %d KB",
        "clipboard.section.pinned":          "Đã ghim",
        "clipboard.section.other":           "Lịch sử",
        "clipboard.purePaste":               "Bỏ định dạng",
        "clipboard.purePaste.tooltip":       "Tự động bỏ định dạng (rich text) khỏi clipboard. Khi paste sẽ ra plain text.",

        "menubar.open":                      "Mở DevPad",
        "menubar.empty":                     "Chưa có mục nào",
        "menubar.quit":                      "Thoát DevPad",

        "dropshelf.title":                   "Khay thả file",
        "dropshelf.empty":                   "Thả file vào đây",
        "dropshelf.hint":                    "Kéo file vào, rồi kéo cả bộ ra một thư mục mới.",
        "dropshelf.count":                   "%d file",
        "dropshelf.clear":                   "Xóa khay",
        "dropshelf.close":                   "Đóng",
        "dropshelf.toggle":                  "Bật",
        "dropshelf.toggleHint":              "Khi bật, khay nổi sẽ tự hiện khi bạn bắt đầu kéo file ở bất kỳ đâu trên máy.",
        "dropshelf.disabled.title":          "Khay thả đang tắt",
        "dropshelf.disabled.hint":           "Bật lên để bắt đầu gom file khi đang kéo.",
        "dropshelf.list.empty":              "Chưa có file nào",
        "dropshelf.list.empty.hint":         "Kéo file vào khay nổi — chúng sẽ hiện ở đây.",
        "dropshelf.remove":                  "Xóa khỏi khay",
        "menubar.tab.clipboard":             "Clipboard",
        "menubar.tab.dropshelf":             "Khay thả file",

        "settings.title":                    "Cài đặt",
        "settings.section.appearance":       "Giao diện",
        "settings.theme":                    "Chế độ",
        "settings.theme.system":             "Theo hệ thống",
        "settings.theme.light":              "Sáng",
        "settings.theme.dark":               "Tối",
        "settings.theme.footer":             "Chọn giao diện cho DevPad. \"Theo hệ thống\" sẽ theo cài đặt macOS.",
        "settings.section.language":         "Ngôn ngữ",
        "settings.language":                 "Ngôn ngữ",
        "settings.language.system":          "Theo hệ thống",
        "settings.language.english":         "English",
        "settings.language.vietnamese":      "Tiếng Việt",
        "settings.language.footer":          "Thay đổi áp dụng ngay, không cần khởi động lại.",

        "settings.section.dropshelf":        "Khay thả file",
        "settings.dropshelf":                "Bật",
        "settings.dropshelf.footer":         "Hiện khay nổi khi bạn bắt đầu kéo file. Thả file vào khay, sau đó kéo cả bộ ra thư mục mới.",

        "settings.section.about":            "Thông tin",
        "settings.about.version":            "Phiên bản",
        "settings.about.copyright":          "Bản quyền",
        "settings.about.copyright.value":    "© 2026 bachbnt. Bảo lưu mọi quyền.",
        "settings.about.license":            "Giấy phép",
        "settings.about.license.value":      "Proprietary",
        "settings.about.license.footer":     "Nghiêm cấm sao chép, chỉnh sửa hoặc phân phối phần mềm này khi chưa có sự cho phép bằng văn bản.",

        "window.minSize":                    "DevPad"
    ]
}
